---

# tasks file for osp.servers


- name: Create the QA servers on OSP
  os_server:
    cloud: openstack
    name: "{{ server.name }}"
    state: "{{ server.state }}"
    image: "{{ server.image }}"
    key_name: "{{ server.key_name }}"
    flavor: "{{ server.flavor }}"
    security_groups: "{{ server.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    #meta: "{{ server.meta }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ osp_servers }}"
  loop_control:  
    loop_var: server 

- name: "Adding floating ip to {{ item }}"
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ osp_servers }}"
  loop_control:
    loop_var: server 
