---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: "{{ repo_file }}"

 
- name: install base tools and packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"


- name: deploy httpd index.html file
  template:
    src: index.html.j2
    dest: "{{ index_file }}"
  notify:
    - "start {{ payload }}"

    